// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDotDeqHUMo7ojwDdIB0yN8gOZmz3qMJoY',
    appId: '1:539805701076:web:11f624946a46244e0a7c41',
    messagingSenderId: '539805701076',
    projectId: 'assignment-tracker-16c81',
    authDomain: 'assignment-tracker-16c81.firebaseapp.com',
    storageBucket: 'assignment-tracker-16c81.firebasestorage.app',
    measurementId: 'G-QZG64SE2FQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt3ldG4VyNLZQ_CAQvdftXr8gwB0ByGHI',
    appId: '1:539805701076:android:15cc1a2b5f14769d0a7c41',
    messagingSenderId: '539805701076',
    projectId: 'assignment-tracker-16c81',
    storageBucket: 'assignment-tracker-16c81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2yYysZNnFDdsOdvZRcEn8PUESoIcOM3c',
    appId: '1:539805701076:ios:ffca6a898b86bb260a7c41',
    messagingSenderId: '539805701076',
    projectId: 'assignment-tracker-16c81',
    storageBucket: 'assignment-tracker-16c81.firebasestorage.app',
    iosBundleId: 'com.assignmenttracker.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2yYysZNnFDdsOdvZRcEn8PUESoIcOM3c',
    appId: '1:539805701076:ios:7d02764625db42fa0a7c41',
    messagingSenderId: '539805701076',
    projectId: 'assignment-tracker-16c81',
    storageBucket: 'assignment-tracker-16c81.firebasestorage.app',
    iosBundleId: 'com.mandm.app.smartassignmenttracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDotDeqHUMo7ojwDdIB0yN8gOZmz3qMJoY',
    appId: '1:539805701076:web:5ea013bbbc0ae4e90a7c41',
    messagingSenderId: '539805701076',
    projectId: 'assignment-tracker-16c81',
    authDomain: 'assignment-tracker-16c81.firebaseapp.com',
    storageBucket: 'assignment-tracker-16c81.firebasestorage.app',
    measurementId: 'G-P54J255K3T',
  );
}
